name: Publish to NPM

on:
  push:
    branches:
      - main
      - v2

jobs:
  publish:
    if: github.repository == 'Technical-Source/bruh'

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - name: Changesets
        id: changesets
        uses: changesets/action@v1
        env:
          NPM_CONFIG_PROVENANCE: true
